model:
  base_learning_rate: 5e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /root/autodl-tmp/v1-5-pruned-no_ema.ckpt
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: train/loss_epoch
    scale_factor: 0.18215
    use_ema: False
    use_adam8bit_optmizer: True # To save VRAM

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1 ] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        # ckpt_path: '/root/autodl-tmp/vae-ft-mse-840000-ema-pruned.ckpt'
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        penultimate: False # use 2nd last layer - https://arxiv.org/pdf/2205.11487.pdf D.1

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.simple.ImageInfoDs
      params:
        root_dir: '/dev/shm/FinalDs/'
        mode: "train"
        ucg: 0.1 # unconditional guidance training
        imageSizeBuckets: [1024]
        resizeStrategy: maxSize
        val_split: 1
    validation:
      target: ldm.data.simple.ImageInfoDs
      params:
        root_dir: '/dev/shm/FinalDs/'
        mode: "val"
        val_split: 1
        ucg: 0.1
        imageSizeBuckets: [1024]
        resizeStrategy: maxSize

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200000000
        max_images: 1
        increase_log_steps: False
        log_first_step: False
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 1
          ddim_steps: 50
  trainer:
      precision: 16
      amp_backend: "native"
      benchmark: True
      limit_val_batches: 1.0
      limit_train_batches: 1.0
      num_sanity_val_steps: 0
      accumulate_grad_batches: 8
      fast_dev_run: False
      check_val_every_n_epoch: null
      #val_check_interval: 4000 # Real train step
  modelcheckpoint:
    params:
      # every_n_train_steps: 501 # Batch step
      save_on_train_epoch_end: True
      save_last: true
